IF OBJECT_ID(N'JTEXT.KATAHIRA', N'FN') IS NOT NULL DROP FUNCTION JTEXT.KATAHIRA;
GO

CREATE FUNCTION JTEXT.KATAHIRA(@KATAKANA AS NVARCHAR(MAX))
  RETURNS NVARCHAR(MAX)

AS
BEGIN
  DECLARE @HIRAGANA AS NVARCHAR(MAX) = N''
  DECLARE @POS AS INT = 0
  DECLARE @TEMPCHAR AS INT

  WHILE @POS <= LEN(@KATAKANA)
    BEGIN
      SET @TEMPCHAR = UNICODE(SUBSTRING(@KATAKANA, @POS, 1))
      IF @TEMPCHAR >= 12449 AND @TEMPCHAR <= 12538
        BEGIN
          SET @TEMPCHAR -= 96
        END;
      SET @HIRAGANA = CONCAT(@HIRAGANA, NCHAR(@TEMPCHAR));
      SET @POS += 1;
  END;
  RETURN @HIRAGANA;
END;
GO
